apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: frontend
          image: mfremash/react-frontend:v0.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

